/*
 * generated by Xtext 2.25.0
 */
package org.xtext.botGenerator;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class BotStandaloneSetup extends BotStandaloneSetupGenerated {

	public static void doSetup() {
		new BotStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
